Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/giovanni/wsn/iot-trust-task-alloc/tools/setup.py", line 407, in <module>
    setup.run()
  File "/home/giovanni/wsn/iot-trust-task-alloc/tools/setup.py", line 74, in run
    self._create_setup_dir()
  File "/home/giovanni/wsn/iot-trust-task-alloc/tools/setup.py", line 112, in _create_setup_dir
    shutil.rmtree("setup")
  File "/usr/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'build_number'
